### PR TITLE
Add pullreview.com

### PR DESCRIPTION
**Pull request by MrSerth**

### CODE REVIEW

**Comment by MrSerth** [comment]
[PullReview stats](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/pullreview)

**Comment by MrSerth** [comment]
[PullReview](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/pullreview?to_sha=1f88c8312b75ff6cc4b27cc93c1dc0819468b093) **[9 to go.](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/pullreview)**

**Comment by MrSerth** [comment]
[PullReview](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/pullreview?to_sha=32fd5d6be7fe525798525dcd9a7e1ce6906b72c0) **[9 to go.](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/pullreview)**

**Comment by MrSerth** [comment]
[PullReview](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/pullreview?to_sha=d3a8876080779d46d1c9f0620f443f5ad6f2202e) **[9 to go.](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/pullreview)**

**Comment by Atyanar** [comment]
:penguin:

**Pull request merged**
