### PR TITLE
Update dependencies (Gemnasium auto-update 449c86eef4cb755ad2e1d46ee55acdb8c6d54a91)

### PR DESCRIPTION
**Pull request by MrSerth**
Update dependencies:
rubocop: 0.35.1 => 0.36.0

### CODE REVIEW

**Comment by rosabraatz** [comment]
:+1:

**Comment by MrSerth** [comment]
As we use rubocop with rubocop-rspec, we should wait upgrading rubocop until rubocop-spec has resolve a [compatibility issue](https://github.com/nevir/rubocop-rspec/issues/62). In addition, rubocop 0.36.0 will add a meta information (as a comment in the second line just below the encoding) about the frozen string literal (which has been introduced in ruby 2.3.0). Therefore, the first run of rubocop 0.36.0 will touch almost every file.

**Comment by MrSerth** [comment]
We should update our dependencies as soon as possible due to the CVE vulnerabilities in Rails.

**Comment by MrSerth** [comment]
Closing this one as there are already newer ones available

**Pull request closed without merging**
