### PR TITLE
Add Coveralls

### PR DESCRIPTION
**Pull request by MrSerth**
Merge after #518

### CODE REVIEW

**Comment by MrSerth** [comment]
[PullReview stats](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls)

**Comment by MrSerth** [comment]
[PullReview](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls?to_sha=9bd4b56ccebfef0c4245efbd5d42bbc3bea184a3) **[9 to go.](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls)**

**Comment by MrSerth** [comment]
[PullReview](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls?to_sha=fb218fb8ab7cc570d743a6724beca0d1c91b0d02) **[13 to go.](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls)**

**Comment by MrSerth** [comment]
[PullReview](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls?to_sha=11018a21ea8fe49520fae0250833da6db82cdcc4) **[9 to go.](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls)**

**Comment by MrSerth** [comment]
[PullReview](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls?to_sha=3aac039a15715e5974ad3bbde68f02686b50cba8) **[Great just fixed 4 issues,  5 to go.](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls)**
[Style](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls) Prefer single quoted strings when you don't need string interpolation or special symbols.[ `spec/spec_helper.rb:11`](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls)
[Style](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls) Prefer single quoted strings when you don't need string interpolation or special symbols.[ `spec/spec_helper.rb:11`](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls)
[Style](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls) Prefer single quoted strings when you don't need string interpolation or special symbols.[ `spec/spec_helper.rb:11`](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls)
[Style](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls) Prefer single quoted strings when you don't need string interpolation or special symbols.[ `spec/spec_helper.rb:11`](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls)

**Comment by Atyanar** [comment]
:koala:

**Comment by MrSerth** [comment]
[PullReview](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls?to_sha=52560a0d1a1a3702ce4088a4aeb9fb872e5e1263) **[5 to go.](https://www.pullreview.com/github/mammooc/mammooc.org/reviews/integrations/coveralls)**

**Pull request merged**
