### PR TITLE
Include specs from TVA

### PR DESCRIPTION
**Pull request by MrSerth**

### CODE REVIEW

**Comment by MrSerth** [comment]
Looks good, just include the following changes 👍
[Update_changes_to_current_mammooc_repo.patch](https://github.com/mammooc/mammooc.org/files/381547/Update_changes_to_current_mammooc_repo.patch.txt)

**Comment by MrSerth** [comment]
I would suggest to ignore the Hakiri security warnings and just merge this commit. The warnings will disappear once it's merged.

**Comment by MrSerth** [comment]
In addition to that, I locally executed the additional specs and may confirm that everything is fine.

**Comment by MrSerth** [comment]
I would suggest to merge that soon without further merging or waiting for the tests to pass. They will once it's merged.

**Comment by Atyanar** [comment]
👍 :shipit:

**Pull request merged**
